---
name: publish
on:
  push:
    tags:
    - v*

jobs:
  publish:
    name: publish to npm
    runs-on: ubuntu-20.04

    steps:
    - name: "checkout code"
      uses: "actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579" # v2.4.0
    - name: "setup node"
      uses: "actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561" # v2.5.1
      with:
        node-version: "16.14.0"
    - name: "setup pnpm"
      run: "npm i -g pnpm@6.30.0"
    - name: "cache pnpm store"
      uses: "actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed" # v2.1.7
      with:
        path: "~/.pnpm-store"
        key: pnpm-store-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          pnpm-store-cache-${{ runner.os }}-
          pnpm-store-cache-
    - name: "install dependencies"
      run: "pnpm i"

    - name: build
      run: pnpm run build
    - name: "publish to npm"
      run: |
        cp .github/.npmrc .npmrc
        VERSION=${GITHUB_REF#refs/*/v} node .github/prepare.cjs
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
